Y:
CD GITGUH
CD COM
CD PROGRAMAS
XCOPY ..\PROGRAMAS ..\RESULTADOS \E 
:: VI QUE SI NO PONIA EL BARRA E NO SE ME PONIAN BIEN. DE TODAS FORMAS POR ERRORES Y LIOS QUE TUBE, CONSEGUI PONERLOS AL FINAL.
:: LOS TRASFERI DOS VECES Y UNA SE SOBRESCRIBIO A SI QUE DEBERIA ESTAR BIEN.

