::ESTOS NO LOS EJECUTO EN EL CMD POR QUE PERDERIA LAS COSAS QUE HICE, POR LO Q NO TIENEN FOTO

::EL 12

CD ..\RESULTADOS
RMDIR /S ..\PROGRAMAS

:: EL 13

CD ..\COM
XCOPY .\* ..\PRINCIPAL/ \E

:: EL 14

RMDIR /S COM